### ISSUE TITLE
Layout distortion when using flags

### ISSUE THREAD

**Issue by captavio** [insilmaril/vym#28] opened 2021-10-28 11:40 UTC
When activating one or more flags, the map layout is shifted to the upper left corner. When disabling the flag again, it is shifted back to the center of the canvas.
With activated flags, it is not possible the shift the layout, it is always fixed in the corner.
Older maps with old flags are not affected.
The effect is strange and hard to descripe, I hope it can be understood.

vym version: 2.8.8 - 2021-06-16
   Platform: openSUSE Leap 15.3
 localeName: de_DE.UTF-8
  tmpVymDir: /tmp/vym-QzNEgC
zipToolPath: /usr/bin/zip
 vymBaseDir: /usr/share/vym
currentPath: /home/01_volker_home
 appDirPath: /usr/bin
   Settings: /home/01_volker_home/.config/InSilmaril/vym.conf
 SSL status: supported
     SSL Qt: OpenSSL 1.1.1d  10 Sep 2019
    SSL lib: OpenSSL 1.1.1d  10 Sep 2019

**Comment by insilmaril** [comment] 2021-10-28 19:13
I see a shift of half the width of the flag, if 

- the map is still smaller than the view (no scrollbars)
- the branch with the flag is right of the map center

Is this what you mean?

This would probably be caused by the changed total bounding box of the map and the view centering on that. Left of the center the new flag already is included within the old bounding box, so the box does not change in that case.

If not, can you maybe do 2 screenshots before/after?

**Comment by captavio** [comment] 2021-10-29 17:00
I made a clean install of opensuse 15.3 with vym 2.8.0 from their repository. Problem did not appear. I try to figure out, what are the differences to my working platform.
Nevertheless I add some screenshots
1) without flags
![Screenshot_20211029_185308_normal](https://user-images.githubusercontent.com/93324001/139473829-0607401d-e19b-4446-8f28-a4423f8aee21.jpg)

2) adding a haert, pls look to the scrollbars

![Screenshot_20211029_185401_with_haert](https://user-images.githubusercontent.com/93324001/139473908-f089b1a2-a7f4-456f-b454-3f95176d8f2b.jpg)

3) Moving cancas to find the map. pls also look to the scrollbars
![Screenshot_20211029_185401_haert_2](https://user-images.githubusercontent.com/93324001/139474396-4b441a1f-1fc0-4a0e-ae0a-fe8e3343dbfe.jpg)

**Comment by insilmaril** [comment] 2021-10-29 18:13
Whoa, that's strange. I don't see why the flag should move the whole map content. At least with my current 2.8.20 I cannot reproduce, but there are no related changes I think. I also run  on 15.3.

I am going to build 2.8.21 in OBS in a couple of days, maybe you can give it a try then

**Comment by captavio** [comment] 2021-10-30 19:31
I made some more tests and found: Files that are based on the new default template are not affected.
Most of my maps are based on a template I created long ago with an older version of vym.
I compared the xml file and found in the field   mapcenter absPosX  very large values but in the newer file these values are small.
Now I changed the position values manually in the file with the problem to small values, saved and reopened in vym and problem was gone
[z1.zip](https://github.com/insilmaril/vym/files/7447487/z1.zip)
.
Hopefully you can reproduce the effect with attached file.
I have no Idea where the large numbers come from.

**Comment by insilmaril** [comment] 2022-01-13 08:11
Closing for now, cannot reproduce.

In case relative positions need to be fixed again, there are two ways:

- in shell using the vivym command to unpack, edit, repack the xml file
- In vym: Use tree editor to select the far off branch, cut, paste to a branch (should reset relative position) and then move to mapcenter again

**Closed as completed by insilmaril** 2022-01-13 08:11 UTC
Labels: bug
