### ISSUE TITLE
Default path not found in Opensuse 15.3

### ISSUE THREAD

**Issue by captavio** [insilmaril/vym#29] opened 2021-10-29 16:43 UTC
In order to figure out the other bugs, I made a clean install of opensuse 15.3 which includes VYM 2.8.0.

When starting VYM , I get an error message "Couldn't read macros form /usr/share/macros/macros/macros.vys" In fact , "vym" is missing in the path.
![Screenshot_20211029_102343_vym_macros](https://user-images.githubusercontent.com/93324001/139471768-aa7b1b06-2f17-4bf3-a857-3b47260c8da4.jpg)

Same thing with "/usr/share/demos/default.vym" . In fact , "vym" is missing in the path here also
![Screenshot_20211029_102430_VYM_default](https://user-images.githubusercontent.com/93324001/139472014-64b9112e-df65-4c81-8bb5-9c7e717a4aa8.jpg)

Finally there is an error message for the update. See screenshot.
![Screenshot_20211029_102611_update](https://user-images.githubusercontent.com/93324001/139472217-9b2bbebf-35fd-4f8c-9783-ab1097f58f9f.jpg)

**Comment by insilmaril** [comment] 2021-10-29 18:48
Duplicate of #14 , fixed meanwhile.

You can also try latest builds from here: 
https://build.opensuse.org/package/show/home:insilmaril/vym

The error message from the webserver is a different thing, if you see that again with a more recent version, I'd be curious about exact time (and maybe your userID to check the logs), maybe better in email

**Closed as completed by insilmaril** 2021-10-29 18:48 UTC
