### ISSUE TITLE
Script editor width

### ISSUE THREAD

**Issue by meptow** [insilmaril/vym#17] opened 2021-07-22 20:50 UTC
Hello insilmaril,

Thanks for VYM! I have used it lightly and now I want to become more advanced. 

I used the -l local option to allow easier modification of the macro file. However, I discovered that the full path to the macro file can increase the minimum displayed width of the script editor. My local macro file has a long path and that made the script editor too wide when docked.

I had hoped to make the displayed path truncate as needed. Unfortunately, my coding skills are not good enough. My ugly "solution" was simply to comment out line 138 in src/scripteditor.cpp:
`//        ui.macrofileLabel->setText(macros.getPath());`

If truncation is an acceptable fix, QSizePolicy::Ignored looks useful. See:
https://stackoverflow.com/a/6721379

**Comment by insilmaril** [comment] 2021-07-25 12:17
Thanks! Ignored doesn't seem to work, maybe I replace the label with a LineEdit, stay tuned...

**Comment by insilmaril** [comment] 2021-07-27 12:50
Fixed in version 2.8.11 with commit 832122a45e1d02a49220aec6980eb175c2771c69

**Closed as completed by insilmaril** 2021-07-27 12:50 UTC
Labels: bug

**Comment by meptow** [comment] 2021-07-29 03:04
832122a allows me to make the script editor window even narrower than my hack, nice! However, if I resize the docked script editor window width and then switch to a different tab (Slide, Macro, Script), the width immediately reverts. I must admit that I applied just the 832122a files to 2.8.8, but based on their history, I don't think it matters.

On a related note, I noticed a "macro" section appear in my ~/.config/InSilmaril/vym.conf (using stock 2.8.8). Is there a document somewhere that describes the format and options of the vym.conf file? I apologize if I missed it.

**Comment by insilmaril** [comment] 2021-07-29 12:29
Hm, I am afraid I cannot reproduce reverting the width. Basically the path is now a QLineEdit (non editable) instead of a label. It should not actively resize anything. Can you try rebuilding the development branch?   Changes are mostly done in Qt designer btw.

For the settings: No, didn't write doc for that yet. Format is usual Qt, wth [section] parts and "\" as separators. vym writes it on closing, I hope most options can be guessed when looking at it

**Comment by meptow** [comment] 2021-07-30 01:41
I'm not able to get the development branch here to compile:
`qmake` reports:
`[...]`
`WARNING: Failure to find: src/userdialog.cpp`
`WARNING: Failure to find: src/userdialog.h`
`WARNING: Failure to find: forms/userdialog.ui`

Pressing on and issuing `make` quickly results in:
`[...]`
`make: *** No rule to make target 'forms/userdialog.ui', needed by 'ui_userdialog.h'.  Stop.`

However, the width reversion described in my last comment is not affecting me today! I had deleted my ~/.config/InSilmaril directory yesterday before using 2.8.8+832122a. The width reversion only seems to happen on the first launch after that deletion.

**Comment by insilmaril** [comment] 2021-08-02 14:58
Ooops. qmake setup is broken, I am trying to fix this, but get interesting compiler errors I don't see with cmake.

You could try 

```
rm Makefile
cmake .
make
```

**Comment by meptow** [comment] 2021-08-04 01:11
I seem to have inadvertently caused the width reversion issue. It's not an issue for me anymore, though I guess it might affect anyone running VYM for the first time.
